name: Greet New Contributors

on:
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet first-time contributor
        if: github.event.pull_request.author_association == 'FIRST_TIMER'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "🎉 WELCOME!!! Thanks for making your first pull request."
